### ISSUE TITLE
Problem with discrete time simulation

### ISSUE THREAD

**Issue by miguelmoreto** [miguelmoreto/labcontrole#15]
A message

Traceback (most recent call last):
  File "LabControle2.py", line 447, in onBtnSimul
  File "MySystem.pyc", line 715, in DiscreteSimulate
  File "scipy\signal\ltisys.pyc", line 568, in lsim2
ValueError: U must have the same number of rows as elements in T.

appears in the log file when the user sets the T parameter to 0,4 using the default LTI system.

**Comment by miguelmoreto** [comment]
This specific error was corrected some time ago. But there are other errors related with this.
If the user sets the number of points/Dt in 21 (for example), there is an error of wrong array dimensions.

**Comment by miguelmoreto** [comment]
Fixed in version 3.
